---
abstract: 'Low level ASE ( Adobe Swatch Exchange ) file Writer.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::Differences: '0'
  Test::More: '0'
  perl: '5.010'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.010'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Color-Swatch-ASE-Writer
provides:
  Color::Swatch::ASE::Writer:
    file: lib/Color/Swatch/ASE/Writer.pm
    version: '0.001003'
recommends:
  Path::Tiny: '0.058'
requires:
  Encode: '0'
  Path::Tiny: '0'
  perl: '5.010'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Color-Swatch-ASE-Writer/issues
  homepage: https://github.com/kentnl/Color-Swatch-ASE-Writer
  repository: https://github.com/kentnl/Color-Swatch-ASE-Writer.git
version: '0.001003'
